### ISSUE TITLE
ng add not working

### ISSUE THREAD

**Issue by bohoffi** [BalticCode/ngx-hotkeys#6]
**Describe the bug**
While using `ng add` to add the library the process stops with an error after the package installation.

**To Reproduce**
```
C:\dev\web\playground>ng add @balticcode/ngx-hotkeys

+ @balticcode/ngx-hotkeys@3.0.0
added 1 package from 1 contributor and audited 17097 packages in 16.825s
found 0 vulnerabilities

Installed packages for tooling via npm.
An unhandled exception occurred: Path "C:\dev\web\playground\node_modules\@balticcode\ngx-hotkeys\schematics\ng-add\schema.json" does not exist.
See "C:\Users\bo_ho\AppData\Local\Temp\ng-Us6ffx\angular-errors.log" for further details.
```
```
[error] Error: Path "C:\dev\web\playground\node_modules\@balticcode\ngx-hotkeys\schematics\ng-add\schema.json" does not exist.
    at readFile (C:\dev\web\playground\node_modules\@angular-devkit\schematics\tools\file-system-utility.js:17:15)
    at Object.readJsonFile (C:\dev\web\playground\node_modules\@angular-devkit\schematics\tools\file-system-utility.js:45:29)
    at NodeModulesEngineHost.createSchematicDescription (C:\dev\web\playground\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:189:48)
    at SchematicEngine.createSchematic (C:\dev\web\playground\node_modules\@angular-devkit\schematics\src\engine\engine.js:219:38)
    at CollectionImpl.createSchematic (C:\dev\web\playground\node_modules\@angular-devkit\schematics\src\engine\engine.js:69:29)
    at AddCommand.getSchematic (C:\dev\web\playground\node_modules\@angular\cli\models\schematic-command.js:135:27)
    at AddCommand.runSchematic (C:\dev\web\playground\node_modules\@angular\cli\models\schematic-command.js:291:32)
    at AddCommand.executeSchematic (C:\dev\web\playground\node_modules\@angular\cli\commands\add-impl.js:148:31)
    at AddCommand.run (C:\dev\web\playground\node_modules\@angular\cli\commands\add-impl.js:114:21)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async AddCommand.validateAndRun (C:\dev\web\playground\node_modules\@angular\cli\models\command.js:134:28)
    at async Object.runCommand (C:\dev\web\playground\node_modules\@angular\cli\models\command-runner.js:185:24)
    at async default_1 (C:\dev\web\playground\node_modules\@angular\cli\lib\cli\index.js:50:31)
```

**Expected behavior**
The process adding the library using the `ng add` schematic should succeed.

**Version information (please complete the following information):**
 - Module 3.0.0
 - Angular 8.2.2

**Comment by bohoffi** [comment]
Closed with a056ce9 v3.0.1
